name: Nations
version: '1.0'
main: me.marcdoesntexists.nations.Nations
api-version: '1.21'
authors:
  - MarcDoesntExists
description: "A comprehensive civilization management plugin for Minecraft"

commands:
  town:
    description: "Manage towns"
    usage: "/town [subcommand]"
    
  kingdom:
    description: "Manage kingdoms"
    usage: "/kingdom [subcommand]"
    
  war:
    description: "Manage warfare"
    usage: "/war [subcommand]"
    
  alliance:
    description: "Manage alliances"
    usage: "/alliance [subcommand]"
    
  religion:
    description: "Manage religions"
    usage: "/religion [subcommand]"
    
  job:
    description: "Manage jobs"
    usage: "/job [subcommand]"
    
  law:
    description: "Manage laws"
    usage: "/law [subcommand]"

permissions:
  nations.admin:
    description: "Admin access to Nations plugin"
    default: op
    
  nations.admin.bypass:
    description: "Bypass protection in claimed chunks"
    default: op
    
  nations.town.create:
    description: "Create towns"
    default: true
    
  nations.kingdom.create:
    description: "Create kingdoms"
    default: true
    
  nations.war.declare:
    description: "Declare wars"
    default: true
    
  nations.alliance.create:
    description: "Create alliances"
    default: true
